version: 1.0.0

# 客户端对police组织的配置部分
client:
  organization: ManufactureOrg
  logging:
    level: info

  eventService:
    timeout:
      connections: 3s
      registrationResponse: 5s
  #    type: eventhub

  global:
    timeout:
      query: 10s
      execute: 2s

  # crypto-config.yaml文件路径，不用写.yaml
  cryptoconfig:
    path: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config

  # 一些SDK支持可插拔KV存储,使用默认即可
  credentialStore:
    path: "/tmp/state-store"
    cryptoStore:
      path: /tmp/msp

  BCCSP:
    security:
    enabled: true
    default:
    provider: "SW"
    hashAlgorithm: "SHA2"
    softVerify: true
    level: 256


# 通道部分
channels:
  # 通道名称
  manufacturechannel:
    # orderer节点的配置
    orderers:
      - orderer.huniuping.com

    peers:  # 对应组织下的所有peer节点，和client中的organization组织保持一致
      peer0.manufacture.huniuping.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.manufacture.huniuping.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.supervise.huniuping.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.supervise.huniuping.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    # 策略配置，使用默认即可
    policies:
      queryChannelConfig:
      minResponses: 1
      maxTargets: 1
      retryOpts:
        attempts: 5
        initialBackoff: 500ms
        maxBackoff: 5s
        backoffFactor: 2.0


# 所有组织 = 所有peer组织 + orderer组织
organizations:
  DesignOrg:
    mspid: DesignMSP
    cryptoPath: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/design.huniuping.com/users/Admin@design.huniuping.com/msp
    peers:
      - peer0.design.huniuping.com
      - peer1.design.huniuping.com

  ProcessOrg:
    mspid: ProcessMSP
    cryptoPath: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/process.huniuping.com/users/Admin@process.huniuping.com/msp
    peers:
      - peer0.process.huniuping.com
      - peer1.process.huniuping.com

  AssembleOrg:
    mspid: AssembleMSP
    cryptoPath: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/assemble.huniuping.com/users/Admin@assemble.huniuping.com/msp
    peers:
      - peer0.assemble.huniuping.com
      - peer1.assemble.huniuping.com

  QualityOrg:
    mspid: QualityMSP
    cryptoPath: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/quality.huniuping.com/users/Admin@quality.huniuping.com/msp
    peers:
      - peer0.quality.huniuping.com
      - peer1.quality.huniuping.com

  ContractOrg:
    mspid: ContractMSP
    cryptoPath: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/contract.huniuping.com/users/Admin@contract.huniuping.com/msp
    peers:
      - peer0.contract.huniuping.com
      - peer1.contract.huniuping.com

  ManufactureOrg:
    mspid: ManufactureMSP
    cryptoPath: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/manufacture.huniuping.com/users/Admin@manufacture.huniuping.com/msp
    peers:
      - peer0.manufacture.huniuping.com
      - peer1.manufacture.huniuping.com

  SuperviseOrg:
    mspid: SuperviseMSP
    cryptoPath: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/supervise.huniuping.com/users/Admin@supervise.huniuping.com/msp
    peers:
      - peer0.supervise.huniuping.com
      - peer1.supervise.huniuping.com

  OrdererOrg:
    mspid: OrdererMSP
    cryptoPath: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/ordererOrganizations/huniuping.com/users/Admin@huniuping.com/msp
    orderers:
      - orderer.huniuping.com
      - orderer2.huniuping.com
      - orderer3.huniuping.com
      - orderer4.huniuping.com
      - orderer5.huniuping.com


# orderer节点
orderers:
  orderer.huniuping.com:
    url: grpcs://localhost:7050  # grpcs://localhost:7050,此URL用于发送背书和查询请求
    grpcOptions:
      ssl-target-name-override: orderer.huniuping.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true # 非tls连接
    tlsCACerts:
      path: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/ordererOrganizations/huniuping.com/tlsca/tlsca.huniuping.com-cert.pem

# peer节点
peers:
  peer0.manufacture.huniuping.com:
    url: grpcs://localhost:23051 # 此URL用于发送背书和查询请求
    eventUrl: grpcs://localhost:23053  # 此URL用于连接EventHub并注册事件侦听器
    grpcOptions:
      ssl-target-name-override: peer0.manufacture.huniuping.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
    tlsCACerts:
      path: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/manufacture.huniuping.com/tlsca/tlsca.manufacture.huniuping.com-cert.pem

  peer1.manufacture.huniuping.com :
    url: grpcs://localhost:24051 # 此URL用于发送背书和查询请求
    eventUrl: grpcs://localhost:24053  # 此URL用于连接EventHub并注册事件侦听器
    grpcOptions:
      ssl-target-name-override: peer1.manufacture.huniuping.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
    tlsCACerts:
      path: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/manufacture.huniuping.com/tlsca/tlsca.manufacture.huniuping.com-cert.pem

  peer0.supervise.huniuping.com:
    url: grpcs://localhost:17051 # 此URL用于发送背书和查询请求
    eventUrl: grpcs://localhost:17053  # 此URL用于连接EventHub并注册事件侦听器
    grpcOptions:
      ssl-target-name-override: peer0.supervise.huniuping.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
    tlsCACerts:
      path: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/supervise.huniuping.com/tlsca/tlsca.supervise.huniuping.com-cert.pem

  peer1.supervise.huniuping.com :
    url: grpcs://localhost:18051 # 此URL用于发送背书和查询请求
    eventUrl: grpcs://localhost:18053  # 此URL用于连接EventHub并注册事件侦听器
    grpcOptions:
      ssl-target-name-override: peer1.supervise.huniuping.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
    tlsCACerts:
      path: /home/myfabric/code/go/src/raft-fabric-project/fabric-network/crypto-config/peerOrganizations/supervise.huniuping.com/tlsca/tlsca.supervise.huniuping.com-cert.pem


